### ISSUE TITLE
Linkedin

### ISSUE THREAD

**Issue by Wesley-Maia** [ricardo-sousa-dev/ricardo-sousa-dev#1]
Ricardo, boa tarde!

Analisando o arquivo "ricardo-sousa-dev/README.md", notei que o badge do Linkedin está direcionando para a página do Fernando.

[![Linkedin Badge](https://img.shields.io/badge/-LinkedIn-0077B5?style=flat-square&logo=Linkedin&logoColor=white&link=https://www.linkedin.com/in/rwmsousa/)](**https://www.linkedin.com/in/fcosta-dev/**)

Abraços,

Wesley

**Comment by rwmsousa** [comment]
Oooooopa, Wesley! Valeu pelo alerta... vou fazer a alteração. Muitíssimo obrigado!
